spring.application.name=SpringEcom

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=3691

spring.jpa.hibernate.ddl-auto=update