spring.application.name=SpringEcom
server.port=8090

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.auto-commit=false

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8090/login/oauth2/code/google

# Github OAuth
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8090/login/oauth2/code/github
spring.security.oauth2.client.registration.github.scope=user:email

# Default user
spring.security.user.name=${SPRING_USER}
spring.security.user.password=${SPRING_PASSWORD}

# JWT
jwt.secret=${JWT_SECRET}

spring.security.oauth2.authorizationserver.client.myclient.registration.client-id=my-client-id
spring.security.oauth2.authorizationserver.client.myclient.registration.client-secret={noop}my-secret
spring.security.oauth2.authorizationserver.client.myclient.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.myclient.registration.authorization-grant-types=authorization_code,refresh_token
spring.security.oauth2.authorizationserver.client.myclient.registration.redirect-uris=http://127.0.0.1:8080/login/oauth2/code/my-client
spring.security.oauth2.authorizationserver.client.myclient.registration.scopes=openid,profile
spring.security.oauth2.authorizationserver.client.myclient.require-authorization-consent=true